-- Criação da Sequence para o ID_USUARIO
CREATE SEQUENCE Seq_ID_Usuario
    AS INT
    START WITH 1
    INCREMENT BY 1;
    
-- Criação da tabela TB_USUARIO
CREATE TABLE TB_USUARIO (
    ID_USUARIO INT PRIMARY KEY DEFAULT NEXT VALUE FOR Seq_ID_Usuario,
    USERNAME NVARCHAR(255) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE
);

-- Criação da Sequence para o EMAIL_ID
CREATE SEQUENCE Seq_Email_ID
    AS UNIQUEIDENTIFIER
    START WITH NEWID()
    INCREMENT BY 1;

-- Criação da tabela TB_EMAIL
CREATE TABLE TB_EMAIL (
    EMAIL_ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEXT VALUE FOR Seq_Email_ID,
    OWNER_REF NVARCHAR(255) NOT NULL,
    EMAIL_FROM NVARCHAR(255) NOT NULL,
    EMAIL_TO NVARCHAR(255) NOT NULL,
    SUBJECT NVARCHAR(255) NOT NULL,
    TEXT CLOB,
    SEND_DATE_EMAIL DATETIME NOT NULL,
    STATUS_EMAIL NVARCHAR(50) NOT NULL
);

-- Criação da Sequence para o ID_SENSOR
CREATE SEQUENCE Seq_ID_Sensor
    AS INT
    START WITH 1
    INCREMENT BY 1;

-- Criação da tabela TB_SENSOR
CREATE TABLE TB_SENSOR (
    ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR Seq_ID_Sensor,
    TYPE NVARCHAR(255) NOT NULL,
    NOME NVARCHAR(255) NOT NULL
);

-- Criação da Sequence para o ID_DEVICE
CREATE SEQUENCE Seq_ID_Device
    AS INT
    START WITH 1
    INCREMENT BY 1;

-- Criação da tabela TB_DEVICES
CREATE TABLE TB_DEVICES (
    ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR Seq_ID_Device,
    NAME NVARCHAR(255) NOT NULL,
    TYPE NVARCHAR(255) NOT NULL,
    SENSOR_ID INT NOT NULL,
    FOREIGN KEY (SENSOR_ID) REFERENCES TB_SENSOR(ID)
);

-- Criação da Sequence para o ID_ENERGY
CREATE SEQUENCE Seq_ID_Energy
    AS INT
    START WITH 1
    INCREMENT BY 1;

-- Criação da tabela TB_ENERGY
CREATE TABLE TB_ENERGY (
    ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR Seq_ID_Energy,
    MONTH NVARCHAR(255) NOT NULL,
    ENERGY_CONSUMED FLOAT NOT NULL,
    DEVICE_ID INT NOT NULL,
    FOREIGN KEY (DEVICE_ID) REFERENCES TB_DEVICES(ID)
);
